<?php if (count($flash) > 0) : ?>
    <ul>
        <?php foreach ($flash as $messages) : ?>
            <?php foreach ($messages as $message) : ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>
<h3>Click on name of post to edit it</h3>

    <div>
        <a href="/posts/<?= $posts['id'] ?>/edit"><?= htmlspecialchars($posts['name']) ?></a>
    </div>

